### ISSUE TITLE
Polling for valid keys every 100ms vs operating only at key inputs

### ISSUE THREAD

**Issue by GaurangTandon** [YoogottamK/vim_browser#5]
The latter is much favorable imo in terms of performance and semantics. Though I agree modern machines can easily handle such polling, I don't see a point in polling as it may be also possible that user isn't pressing anything for a minute (reading a blog, maybe?) and then you're polling 60*1000/100=600 times at that. As the poll handler function increases in size this may become quite a big overhead.

Otoh, putting the poll handler inside the key input handler seems to do the same job and is more performance oriented imo.

**Comment by YoogottamK** [comment]
Lol

I didn't know about all this.

Thanks!

Will work on this.

**Comment by YoogottamK** [comment]
Thoughts on #7?

It is better than before but still doesn't poll only when valid input was detected as I intend to add ore features.
